image: gitlab-registry.cern.ch/ci-tools/ci-worker:slc6

stages:
  - build
  - test
  - test_plotScript

build_cmssw:
  stage: build
  tags:
    - docker
    - cvmfs
  script:
    - pwd
    - ls -l
    - mkdir L1Trigger
    - mv TrackFindingTMTT L1Trigger
    - mv TrackFindingTracklet L1Trigger
    - export SCRAM_ARCH=slc6_amd64_gcc700
    - /cvmfs/cms.cern.ch/common/scramv1 project CMSSW CMSSW_10_4_0
    - mv L1Trigger CMSSW_10_4_0/src/
    - cd CMSSW_10_4_0/src
    - eval `/cvmfs/cms.cern.ch/common/scramv1 runtime -sh`
    - /cvmfs/cms.cern.ch/common/scram b
  artifacts:
    expire_in: 1 day
    paths:
      - CMSSW_10_4_0
  only:
      - merge_requests


build_standalone:
  stage: build
  tags:
    - docker
    - cvmfs
  script:
    - pwd
    - ls -l
    - mkdir L1Trigger
    - mv TrackFindingTMTT L1Trigger
    - mv TrackFindingTracklet L1Trigger
    - cd L1Trigger/TrackFindingTracklet/test/
    - source /cvmfs/sft.cern.ch/lcg/views/LCG_95/x86_64-slc6-gcc7-opt/setup.sh
    - make
  artifacts:
    expire_in: 1 day
    paths:
      - L1Trigger
  only:
      - merge_requests

run_cmssw:
  stage: test
  tags:
    - docker
    - cvmfs
  script:
    - cd CMSSW_10_4_0/src/
    - eval `/cvmfs/cms.cern.ch/common/scramv1 runtime -sh`
    - cd L1Trigger/TrackFindingTracklet/test/
    - export CMS_PATH=/cvmfs/cms-ib.cern.ch/
    - echo "process.source.fileNames = cms.untracked.vstring('file:CI/skimmedForCI.root')" >> L1TrackNtupleMaker_cfg.py
    - echo "process.maxEvents = cms.untracked.PSet(input = cms.untracked.int32(100))" >> L1TrackNtupleMaker_cfg.py
    - echo "process.MessageLogger.cerr.FwkReport.reportEvery = cms.untracked.int32(10)" >> L1TrackNtupleMaker_cfg.py
    - echo cat L1TrackNtupleMaker_cfg.py
    - cmsRun L1TrackNtupleMaker_cfg.py
    - ls -trlh
  dependencies:
    - build_cmssw
  artifacts:
    expire_in: 1 day
    paths:
      - CMSSW_10_4_0
  only:
    - merge_requests

run_plotScript:
  stage: test_plotScript
  tags:
    - docker
    - cvmfs
  script:
    - yum install -y -q http://linuxsoft.cern.ch/wlcg/sl6/x86_64/HEP_OSlibs_SL6-1.1.6-1.el6.x86_64.rpm
    - cd CMSSW_10_4_0/src/
    - eval `/cvmfs/cms.cern.ch/common/scramv1 runtime -sh`
    - cd L1Trigger/TrackFindingTracklet/test/
    - ls -trlh
    - mkdir TrkPlots
    - root -q -b -l -x 'L1TrackNtuplePlot.C("TTbar_PU200_hybrid")'
    - echo $?
  dependencies:
    - run_cmssw
  artifacts:
    expire_in: 1 day
    paths:
      - CMSSW_10_4_0
  only:
    - merge_requests